name: Deploy

on:
  push:
    branches:
      - master
      - dev
      - feature/build-staging

jobs:
  staging:
    runs-on: ubuntu-latest
    name: Staging Deploy
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/feature/build-staging'
    steps:
      - name: ssh pipelines
        uses: appleboy/ssh-action@master
        with:
          host: '${{ secrets.SSH_HOST }}'
          username: '${{ secrets.SSH_USER }}'
          password: '${{ secrets.SSH_PASSWORD }}'
          port: 22
          script: |
            echo "Adding SSH Key"
            eval "$(ssh-agent -s)"
            ssh-add -k ~/.ssh/deploy_aibq_rim

            echo "Cloning repository..."
            cd ~/src
            rm -rf rim-staging
            git clone --branch dev git@github.com:appwapp/aibq.rim.webapp.git rim-staging            

            echo "Installing & building webapp..."
            cd rim-staging/src
            echo '${{ secrets.ENV }}' >> .env
            npm install
            npm run build

            echo "Deploying dist..."
            cp -R ~/src/rim-staging/src/dist/* ~/rim.aibq.qc.ca

  master:
    runs-on: ubuntu-latest
    name: Prod Deploy
    if: github.ref == 'refs/heads/master'
    steps:
      - name: ssh pipelines
        uses: appleboy/ssh-action@master
        with:
          host: '${{ secrets.SSH_HOST }}'
          username: '${{ secrets.SSH_USER }}'
          password: '${{ secrets.SSH_PASSWORD }}'
          port: 22
          script: |
            echo "Adding SSH Key"
            eval "$(ssh-agent -s)"
            ssh-add -k ~/.ssh/deploy_aibq_rim

            echo "Cloning repository..."
            cd ~/src
            rm -rf rim-production
            git clone --branch master git@github.com:appwapp/aibq.rim.webapp.git rim-production

            echo "Installing & building webapp..."
            cd rim-production/src
            echo '${{ secrets.ENV }}' >> .env
            npm install
            npm run build

            echo "Deploying dist..."
            cp -R ~/src/rim-production/src/dist/* ~/rim.aibq.qc.ca
