name: Install & Lint

on:
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '12'

    - name: Install modules
      working-directory: ./src
      run: npm install

    - name: Run ESLint
      working-directory: ./src
      run: npm run lint:quiet